name: Run Bot

on:
  push:
  repository_dispatch:
    types: [restart]

jobs:
  run_bot:
    name: Run Bot
    runs-on: ubuntu-latest

    steps:
      - name: Cancel previous runs
        uses: styfle/cancel-workflow-action@0.5.0
        with:
          access_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Clone repo
        uses: actions/checkout@v2

      - name: Install Dependencies
        run: pip3 install -r requirements.txt

      - name: Run Bot
        run: |
          set +e
          python discordbot.py
        env:
          TOKEN: ${{ secrets.BOT_TOKEN }}

      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          # Optional but recommended
          # Defaults to "Apply automatic changes"
          commit_message: Apply automatic changes

          file_pattern: ./*.json

          # Optional local file path to the repository
          # Defaults to the root of the repository
          repository: .

          # Optional: Skip internal call to `git fetch`
          skip_fetch: true

      - name: Restart Bot
        uses: peter-evans/repository-dispatch@v1
        with:
          token: ${{ secrets.TEST_TOKEN }}
          event-type: restart
          client-payload: '{"runid": "${{ github.run_id }}"}'
